SELECT * FROM MasterPK
SELECT * FROM CustomerPK

SELECT * FROM Customer
SELECT * FROM CustomerML

SELECT * FROM Branch
SELECT * FROM BranchML
SELECT * FROM Org
SELECT * FROM OrgML

SELECT * FROM DEVICE
SELECT * FROM DEVICEML

SELECT * FROM MemberInfo
SELECT * FROM MemberInfoML

SELECT * FROM QSet
SELECT * FROM QSetML
SELECT * FROM QSlide
SELECT * FROM QSlideML
SELECT * FROM QSlideItem
SELECT * FROM QSlideItemML

SELECT * FROM ClientAccess
