DELETE FROM ClientAccess

DELETE FROM DeviceML
DELETE FROM Device

DELETE FROM OrgML
DELETE FROM Org
DELETE FROM BranchML
DELETE FROM Branch

DELETE FROM MemberInfoML
DELETE FROM MemberInfo

DELETE FROM QSlideItemML
DELETE FROM QSlideItem
DELETE FROM QSlideML
DELETE FROM QSlide
DELETE FROM QSetML
DELETE FROM QSet

DELETE FROM CustomerML
DELETE FROM Customer
DELETE FROM CustomerPK

DELETE FROM UserInfoML
DELETE FROM UserInfo

DELETE FROM MasterPK
