SELECT * FROM Language
SELECT * FROM ErrorMessage
SELECT * FROM ErrorMessageML
SELECT * FROM MemberType
SELECT * FROM MemberTypeML
SELECT * FROM LicenseFeature
SELECT * FROM LimitUnit
SELECT * FROM LimitUnitML
SELECT * FROM PeriodUnit
SELECT * FROM PeriodUnitML
SELECT * FROM DeviceType
SELECT * FROM DeviceTypeML
SELECT * FROM UserInfo
SELECT * FROM UserInfoML
